# Generated by Django 5.2.7 on 2025-10-24 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokevar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Pi', 'Pikachu'), ('Ch', 'Charmander'), ('Sq', 'Squirtle'), ('Bu', 'Bulbasaur')], max_length=100)),
            ],
        ),
    ]
